-- Este es un esquema de base de datos PostgreSQL generado a partir del análisis de las migraciones de Laravel.
-- Nota: Las tablas internas de Laravel (cache, jobs, sessions, etc.) han sido omitidas.

-- FASE 1: Tablas de Catálogos (sin dependencias)

CREATE TABLE "cat_carreras" (
    "id_carrera" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "nombre" VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE "cat_roles_equipo" (
    "id_rol_equipo" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "nombre" VARCHAR(50) NOT NULL,
    "descripcion" TEXT
);

CREATE TABLE "cat_roles_sistema" (
    "id_rol_sistema" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "nombre" VARCHAR(20) NOT NULL UNIQUE
);

CREATE TABLE "tokens_jurado" (
    "id_token" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "token" VARCHAR(64) NOT NULL UNIQUE,
    "usado" BOOLEAN NOT NULL DEFAULT FALSE,
    "fecha_expiracion" TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
    "email_invitado" VARCHAR(150)
);

-- FASE 2: Tabla de Usuarios (depende de cat_roles_sistema)

CREATE TABLE "users" (
    "id_usuario" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "nombre" VARCHAR(100) NOT NULL,
    "app_paterno" VARCHAR(100) NOT NULL,
    "app_materno" VARCHAR(100),
    "email" VARCHAR(150) NOT NULL UNIQUE,
    "password" VARCHAR(255) NOT NULL,
    "id_rol_sistema" BIGINT NOT NULL,
    "activo" BOOLEAN NOT NULL DEFAULT TRUE,
    "remember_token" VARCHAR(100),
    "created_at" TIMESTAMP(0) WITHOUT TIME ZONE,
    "updated_at" TIMESTAMP(0) WITHOUT TIME ZONE,
    CONSTRAINT "users_id_rol_sistema_foreign" FOREIGN KEY ("id_rol_sistema") REFERENCES "cat_roles_sistema" ("id_rol_sistema")
);

-- FASE 3: Sub-tablas de Usuarios (dependen de users y catálogos)

CREATE TABLE "estudiantes" (
    "id_usuario" BIGINT PRIMARY KEY,
    "numero_control" VARCHAR(20) NOT NULL UNIQUE,
    "semestre" INTEGER NOT NULL,
    "id_carrera" BIGINT NOT NULL,
    CONSTRAINT "estudiantes_id_usuario_foreign" FOREIGN KEY ("id_usuario") REFERENCES "users" ("id_usuario") ON DELETE CASCADE,
    CONSTRAINT "estudiantes_id_carrera_foreign" FOREIGN KEY ("id_carrera") REFERENCES "cat_carreras" ("id_carrera")
);

CREATE TABLE "jurados" (
    "id_usuario" BIGINT PRIMARY KEY,
    "cedula_profesional" VARCHAR(50),
    "especialidad" VARCHAR(100),
    "empresa_institucion" VARCHAR(100),
    CONSTRAINT "jurados_id_usuario_foreign" FOREIGN KEY ("id_usuario") REFERENCES "users" ("id_usuario") ON DELETE CASCADE
);

-- FASE 4: Tablas de Eventos y Equipos

CREATE TABLE "eventos" (
    "id_evento" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "nombre" VARCHAR(150) NOT NULL,
    "descripcion" TEXT,
    "ruta_imagen" VARCHAR(255),
    "fecha_inicio" TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
    "fecha_fin" TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
    "cupo_max_equipos" INTEGER NOT NULL,
    "estado" VARCHAR(255) NOT NULL DEFAULT 'Próximo' CHECK ("estado" IN ('Próximo', 'Activo', 'Cerrado', 'Finalizado')),
    "deleted_at" TIMESTAMP(0) WITHOUT TIME ZONE
);

CREATE TABLE "equipos" (
    "id_equipo" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "nombre" VARCHAR(100) NOT NULL,
    "ruta_imagen" VARCHAR(255),
    "created_at" TIMESTAMP(0) WITHOUT TIME ZONE,
    "updated_at" TIMESTAMP(0) WITHOUT TIME ZONE
);

-- FASE 5: Tablas de Conexión (muchas dependencias)

CREATE TABLE "evento_jurados" (
    "id_evento" BIGINT NOT NULL,
    "id_jurado" BIGINT NOT NULL,
    "rol_en_evento" VARCHAR(50) NOT NULL DEFAULT 'Evaluador General',
    PRIMARY KEY ("id_evento", "id_jurado"),
    CONSTRAINT "evento_jurados_id_evento_foreign" FOREIGN KEY ("id_evento") REFERENCES "eventos" ("id_evento") ON DELETE CASCADE,
    CONSTRAINT "evento_jurados_id_jurado_foreign" FOREIGN KEY ("id_jurado") REFERENCES "jurados" ("id_usuario") ON DELETE CASCADE
);

CREATE TABLE "inscripciones_evento" (
    "id_inscripcion" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "id_equipo" BIGINT NOT NULL,
    "id_evento" BIGINT NOT NULL,
    "codigo_acceso_equipo" VARCHAR(20),
    "fecha_inscripcion" TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "puesto_ganador" INTEGER,
    "status_registro" VARCHAR(255) NOT NULL DEFAULT 'Incompleto' CHECK ("status_registro" IN ('Incompleto', 'Completo', 'Descalificado')),
    UNIQUE ("id_equipo", "id_evento"),
    CONSTRAINT "inscripciones_evento_id_equipo_foreign" FOREIGN KEY ("id_equipo") REFERENCES "equipos" ("id_equipo") ON DELETE CASCADE,
    CONSTRAINT "inscripciones_evento_id_evento_foreign" FOREIGN KEY ("id_evento") REFERENCES "eventos" ("id_evento") ON DELETE CASCADE
);

CREATE TABLE "miembros_equipo" (
    "id_miembro" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "id_inscripcion" BIGINT NOT NULL,
    "id_estudiante" BIGINT NOT NULL,
    "id_rol_equipo" BIGINT NOT NULL,
    "es_lider" BOOLEAN NOT NULL DEFAULT FALSE,
    UNIQUE ("id_inscripcion", "id_estudiante"),
    CONSTRAINT "miembros_equipo_id_inscripcion_foreign" FOREIGN KEY ("id_inscripcion") REFERENCES "inscripciones_evento" ("id_inscripcion") ON DELETE CASCADE,
    CONSTRAINT "miembros_equipo_id_estudiante_foreign" FOREIGN KEY ("id_estudiante") REFERENCES "estudiantes" ("id_usuario"),
    CONSTRAINT "miembros_equipo_id_rol_equipo_foreign" FOREIGN KEY ("id_rol_equipo") REFERENCES "cat_roles_equipo" ("id_rol_equipo")
);

CREATE TABLE "solicitudes_union" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "equipo_id" BIGINT NOT NULL,
    "estudiante_id" BIGINT NOT NULL,
    "status" VARCHAR(255) NOT NULL DEFAULT 'pendiente' CHECK ("status" IN ('pendiente', 'aceptada', 'rechazada')),
    "mensaje" TEXT,
    "created_at" TIMESTAMP(0) WITHOUT TIME ZONE,
    "updated_at" TIMESTAMP(0) WITHOUT TIME ZONE,
    UNIQUE ("equipo_id", "estudiante_id"),
    CONSTRAINT "solicitudes_union_equipo_id_foreign" FOREIGN KEY ("equipo_id") REFERENCES "equipos" ("id_equipo") ON DELETE CASCADE,
    CONSTRAINT "solicitudes_union_estudiante_id_foreign" FOREIGN KEY ("estudiante_id") REFERENCES "estudiantes" ("id_usuario") ON DELETE CASCADE
);

-- FASE 6: Tablas de Proyectos y Seguimiento

CREATE TABLE "proyectos" (
    "id_proyecto" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "id_inscripcion" BIGINT NOT NULL UNIQUE,
    "nombre" VARCHAR(200) NOT NULL,
    "descripcion_tecnica" TEXT,
    "repositorio_url" VARCHAR(255),
    "created_at" TIMESTAMP(0) WITHOUT TIME ZONE,
    "updated_at" TIMESTAMP(0) WITHOUT TIME ZONE,
    CONSTRAINT "proyectos_id_inscripcion_foreign" FOREIGN KEY ("id_inscripcion") REFERENCES "inscripciones_evento" ("id_inscripcion") ON DELETE CASCADE
);

CREATE TABLE "tareas_proyecto" (
    "id_tarea" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "id_proyecto" BIGINT NOT NULL,
    "descripcion" VARCHAR(255) NOT NULL,
    "completada" BOOLEAN NOT NULL DEFAULT FALSE,
    "completada_por" BIGINT,
    "fecha_completada" TIMESTAMP(0) WITHOUT TIME ZONE,
    "created_at" TIMESTAMP(0) WITHOUT TIME ZONE,
    "updated_at" TIMESTAMP(0) WITHOUT TIME ZONE,
    CONSTRAINT "tareas_proyecto_id_proyecto_foreign" FOREIGN KEY ("id_proyecto") REFERENCES "proyectos" ("id_proyecto") ON DELETE CASCADE,
    CONSTRAINT "tareas_proyecto_completada_por_foreign" FOREIGN KEY ("completada_por") REFERENCES "users" ("id_usuario")
);

CREATE TABLE "avances" (
    "id_avance" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "id_proyecto" BIGINT NOT NULL,
    "titulo" VARCHAR(100),
    "descripcion" TEXT,
    "url_archivo" VARCHAR(255),
    "fecha_entrega" TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "avances_id_proyecto_foreign" FOREIGN KEY ("id_proyecto") REFERENCES "proyectos" ("id_proyecto") ON DELETE CASCADE
);

CREATE TABLE "evaluaciones" (
    "id_evaluacion" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "id_avance" BIGINT NOT NULL,
    "id_jurado" BIGINT NOT NULL,
    "calificacion" DECIMAL(5, 2) NOT NULL,
    "retroalimentacion" TEXT,
    "fecha_evaluacion" TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE ("id_avance", "id_jurado"),
    CONSTRAINT "evaluaciones_id_avance_foreign" FOREIGN KEY ("id_avance") REFERENCES "avances" ("id_avance") ON DELETE CASCADE,
    CONSTRAINT "evaluaciones_id_jurado_foreign" FOREIGN KEY ("id_jurado") REFERENCES "jurados" ("id_usuario")
);

-- FASE 7: Tabla de Constancias

CREATE TABLE "constancias" (
    "id_constancia" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "id_usuario" BIGINT NOT NULL,
    "id_evento" BIGINT NOT NULL,
    "tipo" VARCHAR(50) NOT NULL,
    "folio_uuid" UUID NOT NULL,
    "url_descarga" VARCHAR(255),
    "created_at" TIMESTAMP(0) WITHOUT TIME ZONE,
    "updated_at" TIMESTAMP(0) WITHOUT TIME ZONE,
    CONSTRAINT "constancias_id_usuario_foreign" FOREIGN KEY ("id_usuario") REFERENCES "users" ("id_usuario"),
    CONSTRAINT "constancias_id_evento_foreign" FOREIGN KEY ("id_evento") REFERENCES "eventos" ("id_evento")
);
